### ISSUE TITLE
Suggestion for Code

### ISSUE THREAD

**Issue by Zer0-Official** [MrMazzone/easy-draw#6]
There is only one large .py file. May I suggest creating a `files` folder and separating your code into multiple files. You can import them into the main file. This would improve organization. Other than that, I love this program. I am open to being added as a project contributor if you want.

**Comment by MrMazzone** [comment]
Hi @Zer0-Official !  Thanks for the comment.  I absolutely agree; however, I want teachers to be able to use this module with ease.  I plan on adding this lib to PyPI eventually, but I also want the code to be contained in one .py file so teachers can simply include it in a students' project directory to use it.  Make sense?

I would love for you to contribute!  Do you mind forking the repo and submitting pull requests for me to approve?
